// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"incidex/internal/config"
	"incidex/internal/db"
	"incidex/internal/infrastructure/cache"
	"incidex/internal/infrastructure/notification"
	"incidex/internal/infrastructure/persistence"
	"incidex/internal/infrastructure/storage"
	"incidex/internal/interface/http/handler"
	"incidex/internal/interface/http/middleware"
	"incidex/internal/pkg/logger"
	"incidex/internal/usecase"
	"time"
)

// InitializeApp creates a fully-wired App with all dependencies.
func InitializeApp(cfg *config.Config) (*App, error) {
	// Config values
	jwtSecret := ProvideJWTSecret(cfg)
	frontendURL := ProvideFrontendURL(cfg)
	jwtExpiry := ProvideJWTExpiry()
	isProduction := ProvideIsProduction(cfg)

	// Infrastructure
	gormDB := db.Connect(cfg.DatabaseURL, logger.Log, cfg.DBLogLevel)
	redisClient := db.ConnectRedis(cfg.RedisURL)
	minIOStorage, err := storage.NewMinIOStorage(
		cfg.MinioEndpoint,
		cfg.MinioAccessKey,
		cfg.MinioSecretKey,
		storage.DefaultBucketName,
		bool(isProduction),
	)
	if err != nil {
		return nil, err
	}
	cacheRepository := cache.NewRedisCache(redisClient)

	// Repositories
	userRepository := persistence.NewUserRepository(gormDB)
	refreshTokenRepository := persistence.NewRefreshTokenRepository(gormDB)
	passwordResetTokenRepository := persistence.NewPasswordResetTokenRepository(gormDB)
	tagRepository := persistence.NewTagRepository(gormDB)
	incidentRepository := persistence.NewIncidentRepository(gormDB)
	incidentActivityRepository := persistence.NewIncidentActivityRepository(gormDB)
	notificationSettingRepository := persistence.NewNotificationSettingRepository(gormDB)
	attachmentRepository := persistence.NewAttachmentRepository(gormDB)
	postMortemRepository := persistence.NewPostMortemRepository(gormDB)
	actionItemRepository := persistence.NewActionItemRepository(gormDB)
	auditLogRepository := persistence.NewAuditLogRepository(gormDB)
	reportRepository := persistence.NewReportRepository(gormDB)

	// Services
	emailService := notification.NewEmailService(string(frontendURL))
	notificationService := notification.NewNotificationService(
		notificationSettingRepository,
		userRepository,
		string(frontendURL),
	)

	// Usecases
	authUsecase := usecase.NewAuthUsecase(
		userRepository,
		refreshTokenRepository,
		string(jwtSecret),
		time.Duration(jwtExpiry),
	)
	passwordResetUsecase := usecase.NewPasswordResetUsecase(
		userRepository,
		passwordResetTokenRepository,
		emailService,
		string(frontendURL),
	)
	tagUsecase := usecase.NewTagUsecase(tagRepository)
	userUsecase := usecase.NewUserUsecase(userRepository)
	statsUsecase := usecase.NewStatsUsecase(incidentRepository, cacheRepository)
	incidentActivityUsecase := usecase.NewIncidentActivityUsecase(
		incidentActivityRepository,
		incidentRepository,
		userRepository,
		notificationService,
	)
	attachmentUsecase := usecase.NewAttachmentUsecase(
		attachmentRepository,
		incidentRepository,
		minIOStorage,
	)
	postMortemUsecase := usecase.NewPostMortemUsecase(
		postMortemRepository,
		incidentRepository,
		incidentActivityRepository,
		userRepository,
	)
	incidentUsecase := usecase.NewIncidentUsecase(
		incidentRepository,
		tagRepository,
		userRepository,
		incidentActivityRepository,
		postMortemRepository,
		notificationService,
		cacheRepository,
	)
	actionItemUsecase := usecase.NewActionItemUsecase(actionItemRepository, postMortemRepository)
	auditLogUsecase := usecase.NewAuditLogUsecase(auditLogRepository)
	reportUsecase := usecase.NewReportUsecase(reportRepository)
	notificationUsecase := usecase.NewNotificationUsecase(notificationSettingRepository)

	// Handlers
	authHandler := handler.NewAuthHandler(authUsecase, bool(isProduction))
	passwordResetHandler := handler.NewPasswordResetHandler(passwordResetUsecase)
	tagHandler := handler.NewTagHandler(tagUsecase)
	incidentHandler := handler.NewIncidentHandler(incidentUsecase)
	userHandler := handler.NewUserHandler(userUsecase)
	statsHandler := handler.NewStatsHandler(statsUsecase)
	activityHandler := handler.NewIncidentActivityHandler(incidentActivityUsecase)
	exportHandler := handler.NewExportHandler(incidentUsecase)
	attachmentHandler := handler.NewAttachmentHandler(attachmentUsecase)
	notificationHandler := handler.NewNotificationHandler(notificationUsecase)
	postMortemHandler := handler.NewPostMortemHandler(postMortemUsecase)
	actionItemHandler := handler.NewActionItemHandler(actionItemUsecase)
	auditLogHandler := handler.NewAuditLogHandler(auditLogUsecase)
	reportHandler := handler.NewReportHandler(reportUsecase)
	healthHandler := handler.NewHealthHandler(gormDB)

	// Middleware
	jwtMiddleware := middleware.NewJWTMiddleware(string(jwtSecret))
	auditMiddleware := middleware.NewAuditMiddleware(auditLogRepository, userRepository)
	loginRateLimiter := middleware.NewRateLimitMiddleware(redisClient, 5, 1*time.Minute)
	apiRateLimiter := middleware.NewRateLimitMiddleware(redisClient, 100, 1*time.Minute)

	return &App{
		Config:               cfg,
		DB:                   gormDB,
		Redis:                redisClient,
		AuthHandler:          authHandler,
		PasswordResetHandler: passwordResetHandler,
		TagHandler:           tagHandler,
		IncidentHandler:      incidentHandler,
		UserHandler:          userHandler,
		StatsHandler:         statsHandler,
		ActivityHandler:      activityHandler,
		ExportHandler:        exportHandler,
		AttachmentHandler:    attachmentHandler,
		NotificationHandler:  notificationHandler,
		PostMortemHandler:    postMortemHandler,
		ActionItemHandler:    actionItemHandler,
		AuditLogHandler:      auditLogHandler,
		ReportHandler:        reportHandler,
		HealthHandler:        healthHandler,
		JWTMiddleware:        jwtMiddleware,
		AuditMiddleware:      auditMiddleware,
		LoginRateLimiter:     loginRateLimiter,
		APIRateLimiter:       apiRateLimiter,
	}, nil
}
